C: [0.1, 1, 10, 100, 1000]
kernel: ["linear", "poly", "rbf", "sigmoid"]
degree: [2, 3, 4]
gamma: ["scale", "auto", 0.001, 0.01, 0.1, 1]
coef0: [0.0, 0.1, 0.5, 1.0]
shrinking: [true, false]
probability: [true]
tol: [1.0e-3, 1.0e-4, 1.0e-5]
cache_size: [100]
class_weight: [null, "balanced"]
verbose: [false]
max_iter: [10000]
decision_function_shape: ["ovo", "ovr"]
break_ties: [false, true]
random_state: [0]